#pragma once
#import <Foundation/Foundation.h>
#import <simd/simd.h>

typedef struct {
    vector_float2 outputResolution;
    vector_float2 sourceResolution;
    vector_float2 cardOrigin;
    float radius;
    float bezelWidth;
    float glassThickness;
    float refractionScale;
    float refractiveIndex;
    float blurRadius;
    float specularOpacity;
    float specularAngle;
    vector_float4 tintColor;
} LGIOS12LiveUniforms;

static NSString * const kLGIOS12LiveMetalSource = @
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"struct Uniforms {\n"
"  float2 outputResolution; float2 sourceResolution; float2 cardOrigin;\n"
"  float radius; float bezelWidth; float glassThickness; float refractionScale;\n"
"  float refractiveIndex; float blurRadius; float specularOpacity; float specularAngle;\n"
"  float4 tintColor;\n"
"};\n"
"float surfaceConvexSquircle(float x) { return pow(1.0-pow(1.0-x,4.0),0.25); }\n"
"float2 refractRay(float2 normal,float eta) {\n"
"  float cosI=-normal.y; float k=1.0-eta*eta*(1.0-cosI*cosI);\n"
"  if(k<0.0) return float2(0.0); float root=sqrt(k);\n"
"  return float2(-(eta*cosI+root)*normal.x, eta-(eta*cosI+root)*normal.y);\n"
"}\n"
"float rawRefraction(float ratio,float thickness,float bezel,float eta) {\n"
"  float x=clamp(ratio,0.05,0.95); float y=surfaceConvexSquircle(x);\n"
"  float derivative=(surfaceConvexSquircle(x+0.001)-y)/0.001;\n"
"  float magnitude=sqrt(derivative*derivative+1.0);\n"
"  float2 ray=refractRay(float2(-derivative/magnitude,-1.0/magnitude),eta);\n"
"  if(length(ray)<0.0001 || abs(ray.y)<0.0001) return 0.0;\n"
"  return ray.x*(y*bezel+thickness)/ray.y;\n"
"}\n"
"float displacement(float ratio,float thickness,float bezel,float eta) {\n"
"  float peak=rawRefraction(0.05,thickness,bezel,eta);\n"
"  if(abs(peak)<0.0001) return 0.0;\n"
"  return (rawRefraction(ratio,thickness,bezel,eta)/peak)*(1.0-smoothstep(0.0,1.0,ratio));\n"
"}\n"
"kernel void liquidGlassIOS12(texture2d<float,access::sample> source [[texture(0)]],\n"
"                             texture2d<float,access::write> output [[texture(1)]],\n"
"                             constant Uniforms &u [[buffer(0)]],\n"
"                             uint2 gid [[thread_position_in_grid]]) {\n"
"  uint W=output.get_width(), H=output.get_height(); if(gid.x>=W || gid.y>=H) return;\n"
"  constexpr sampler s(filter::linear,address::clamp_to_edge);\n"
"  float2 px=float2(gid)+0.5; float2 halfSize=u.outputResolution*0.5;\n"
"  float radius=min(u.radius,min(halfSize.x,halfSize.y)); float2 p=px-halfSize;\n"
"  float2 q=abs(p)-(halfSize-float2(radius));\n"
"  float signedDistance=length(max(q,float2(0.0)))+min(max(q.x,q.y),0.0)-radius;\n"
"  float edgeAlpha=clamp(0.5-signedDistance,0.0,1.0);\n"
"  if(edgeAlpha<=0.0){ output.write(float4(0.0),gid); return; }\n"
"  float edgeDistance=max(0.0,-signedDistance); float2 innerHalf=max(halfSize-float2(radius),float2(0.0));\n"
"  float2 cornerDelta=p-clamp(p,-innerHalf,innerHalf); float2 dir;\n"
"  if(length(cornerDelta)>0.001) dir=normalize(cornerDelta);\n"
"  else { float dx=halfSize.x-abs(p.x), dy=halfSize.y-abs(p.y);\n"
"         dir=(dx<dy)?float2(p.x<0.0?-1.0:1.0,0.0):float2(0.0,p.y<0.0?-1.0:1.0); }\n"
"  float bezel=max(u.bezelWidth,1.0); float ratio=clamp(edgeDistance/bezel,0.0,1.0);\n"
"  float normDisp=edgeDistance<bezel?displacement(ratio,u.glassThickness,bezel,1.0/max(u.refractiveIndex,1.001)):0.0;\n"
"  float2 dispPx=-dir*normDisp*bezel*u.refractionScale;\n"
"  float2 sampleUV=clamp((u.cardOrigin+px+dispPx)/u.sourceResolution,0.0,1.0);\n"
"  float2 texel=1.0/u.sourceResolution; float blurStep=max(1.0,u.blurRadius*0.35);\n"
"  float4 sharp=source.sample(s,sampleUV);\n"
"  float4 blurred=sharp*0.24;\n"
"  blurred+=source.sample(s,sampleUV+float2( blurStep,0.0)*texel)*0.11;\n"
"  blurred+=source.sample(s,sampleUV+float2(-blurStep,0.0)*texel)*0.11;\n"
"  blurred+=source.sample(s,sampleUV+float2(0.0, blurStep)*texel)*0.11;\n"
"  blurred+=source.sample(s,sampleUV+float2(0.0,-blurStep)*texel)*0.11;\n"
"  blurred+=source.sample(s,sampleUV+float2( blurStep, blurStep)*texel)*0.08;\n"
"  blurred+=source.sample(s,sampleUV+float2(-blurStep, blurStep)*texel)*0.08;\n"
"  blurred+=source.sample(s,sampleUV+float2( blurStep,-blurStep)*texel)*0.08;\n"
"  blurred+=source.sample(s,sampleUV+float2(-blurStep,-blurStep)*texel)*0.08;\n"
"  float4 color=mix(sharp,blurred,0.62);\n"
"  color.rgb=mix(color.rgb,u.tintColor.rgb,u.tintColor.a);\n"
"  float2 lightDir=float2(cos(u.specularAngle),-sin(u.specularAngle));\n"
"  float stroke=clamp(1.0-edgeDistance/max(2.0,bezel*0.20),0.0,1.0);\n"
"  float lobe=pow(clamp(abs(dot(dir,lightDir)),0.0,1.0),7.0);\n"
"  float fresnel=pow(clamp(1.0-ratio,0.0,1.0),2.2);\n"
"  float highlight=(lobe*stroke*u.specularOpacity)+(fresnel*0.16);\n"
"  color.rgb=mix(color.rgb,float3(1.0),clamp(highlight,0.0,0.55));\n"
"  output.write(float4(color.rgb,edgeAlpha*0.96),gid);\n"
"}\n"
"struct PresentOut { float4 position [[position]]; float2 uv; };\n"
"// DIAGNOSTIC: raw source crop, no refraction/displacement/blur/tint/\n"
"// Fresnel/specular. Samples the source at exactly the card's screen\n"
"// coordinates so any spatial or orientation error is visible BEFORE any\n"
"// Liquid Glass math. Corner markers identify output->screen mapping:\n"
"//   RED = card top-left, GREEN = card top-right, BLUE = card bottom-left.\n"
"// If RED appears at the card's bottom-left on device, the vertical flip is\n"
"// in the output/present stage. If the markers are correct but the imagery\n"
"// is inverted, the flip is upstream in capture/upload.\n"
"kernel void rawBackdropIOS12(texture2d<float,access::sample> source [[texture(0)]],\n"
"                             texture2d<float,access::write> output [[texture(1)]],\n"
"                             constant Uniforms &u [[buffer(0)]],\n"
"                             uint2 gid [[thread_position_in_grid]]) {\n"
"  uint W=output.get_width(), H=output.get_height(); if(gid.x>=W || gid.y>=H) return;\n"
"  constexpr sampler s(filter::linear,address::clamp_to_edge);\n"
"  float2 px=float2(gid)+0.5;\n"
"  float2 uv=clamp((u.cardOrigin+px)/u.sourceResolution,0.0,1.0);\n"
"  float4 c=source.sample(s,uv);\n"
"  uint m=14;\n"
"  if(gid.x<m && gid.y<m) c=float4(1.0,0.0,0.0,1.0);\n"
"  else if(gid.x>=W-m && gid.y<m) c=float4(0.0,1.0,0.0,1.0);\n"
"  else if(gid.x<m && gid.y>=H-m) c=float4(0.0,0.0,1.0,1.0);\n"
"  output.write(float4(c.rgb,1.0),gid);\n"
"}\n"
"vertex PresentOut presentVertex(uint vertexID [[vertex_id]]) {\n"
"  float2 positions[3]={float2(-1.0,-1.0),float2(3.0,-1.0),float2(-1.0,3.0)};\n"
"  float2 uvs[3]={float2(0.0,1.0),float2(2.0,1.0),float2(0.0,-1.0)};\n"
"  PresentOut out; out.position=float4(positions[vertexID],0.0,1.0); out.uv=uvs[vertexID]; return out;\n"
"}\n"
"fragment float4 presentFragment(PresentOut in [[stage_in]],\n"
"                                texture2d<float,access::sample> image [[texture(0)]]) {\n"
"  constexpr sampler s(filter::linear,address::clamp_to_edge); return image.sample(s,in.uv);\n"
"}\n";
